### ISSUE TITLE
NPE during org.cristalise.kernel.entity.proxy.ProxyClientConnection.<init>

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#106]
Time-to-time during the Gateway.startServer() the following exceptions is thrown:

Here are the logs 
`ProxyManager - Starting.....
Searching for (|(cristalprop=Type:Server)(cristalprop=!Type:Server)) in cn=servers,cn=domain,cn=integTest,cn=cristal,o=cern,c=ch
Gateway.connect() - DONE.
Initializing LDAP Boot tree
SimpleTCPIPServer.run() - Created server for org.cristalise.kernel.scripting.ScriptConsole on port 8888
ProxyManager::initServer - Starting.....
ProxyManager::initServer - Initialising proxy informer on port 1555
SimpleTCPIPServer.run() - Created server for org.cristalise.kernel.entity.proxy.ProxyClientConnection on port 1555
ERROR  : SimpleTCPIPServer.run(): Fatal Error. Listener for 'org.cristalise.kernel.entity.proxy.ProxyClientConnection' will stop.
EXCEPTION:java.lang.NullPointerException
	at org.cristalise.kernel.entity.proxy.ProxyClientConnection.<init>(ProxyClientConnection.java:62)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at java.lang.Class.newInstance0(Class.java:372)
	at java.lang.Class.newInstance(Class.java:325)
	at org.cristalise.kernel.utils.server.SimpleTCPIPServer.run(SimpleTCPIPServer.java:101)
	at java.lang.Thread.run(Thread.java:722)

SimpleTCPIPServer - Servers still running: 1
Gateway.startServer() - ORB initialised. ORB class:'com.sun.corba.se.impl.orb.ORBImpl'`

**Comment by kovax** [comment]
Due to this the ProxyClientConnection is not initialised, therefor none of the Client proxies are informed of changes. That is very important for Agents with persistent JonList.

**Comment by kovax** [comment]
The issue is , that the ProxyServer contructor create the ProxyClientConnection TCP/IP server, which tries to register with the ProxyServer itself in its constructor.
