### ISSUE TITLE
Include mechanism of Script does not find decreaded method when using groovy language

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#124]
The method getValidWeight()() is decraled in a separate Script xml and included in the ComputeWeight xml. Executing ComputeWeight throws the exception bellow, because it does not find the getValidWeight().

For reference including function works for javascript, check usage of DescriptionCollVersionLib.

```
Script.setScriptData()` - Compiling script ComputeWeight
LocalObjectLoader.getScript(WeighbridgeScriptLib v0)
ProxyManager.createProxy() - Item:/entity/f0882d2d-70fd-404b-a526-92f66bb802aa
LocalObjectLoader.getSchema(Script v0)
Script.setScriptData() - Compiling script WeighbridgeScriptLib
Script.execute() - Executing imported script name:WeighbridgeScriptLib version:0
Script.execute() - Output parameter errors = 
LocalObjectLoader.getSchema(TransactionDetails v0)
ProxyManager.createProxy() - Item:/entity/de6e80af-d17f-4b3b-a964-c5eeb994ec01
LocalObjectLoader.getSchema(Schema v0)
Script:ComputeWeight - Setting weightType:Gross
EXCEPTION:javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getValidWeight() is applicable for argument types: (org.cristalise.kernel.persistency.outcome.Outcome) values: [org.cristalise.kernel.persistency.outcome.Outcome@53f54844]
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:346)
	at org.codehaus.groovy.jsr223.GroovyCompiledScript.eval(GroovyCompiledScript.java:72)
	at org.cristalise.kernel.scripting.Script.execute(Script.java:599)
	at org.cristalise.kernel.entity.proxy.AgentProxy.callScript(AgentProxy.java:175)
	at org.cristalise.kernel.entity.proxy.AgentProxy.execute(AgentProxy.java:132)
	at org.cristalise.gui.tabs.execution.DefaultExecutor.execute(DefaultExecutor.java:48)
	at org.cristalise.gui.tabs.execution.ActivityViewer.run(ActivityViewer.java:335)
	at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getValidWeight() is applicable for argument types: (org.cristalise.kernel.persistency.outcome.Outcome) values: [org.cristalise.kernel.persistency.outcome.Outcome@53f54844]
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:415)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.access$000(GroovyScriptEngineImpl.java:97)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl$2.invokeMethod(GroovyScriptEngineImpl.java:329)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at Script1.run(Script1.groovy:45)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:343)
	... 7 more
```

**Comment by kovax** [comment]
My test case still does not work. See test class in dsl project:

https://github.com/cristal-ise/dsl/blob/master/src/test/groovy/org/cristalise/kernel/test/scripting/ScriptExecutionSpecs.groovy
