### ISSUE TITLE
Exception is thrown after editing workflow with swingui

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#232]
The EditingDefinition of CompsoiteActivityDef tirggers the `CompositeActivityDefCollSetter `Script:

Excception in GUI:
```
ClusterStorageManager.get() - found /entity/3f01a50a-1361-4f1d-969e-260458979088/Collection/Activity/last in memcache
EXCEPTION:org.mozilla.javascript.WrappedException: Wrapped org.cristalise.kernel.common.InvalidDataException: IDL:org.cristalise.kernel/common/InvalidDataException:1.0 (CompositeActivityDefCollSetter#34)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1932)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1573)
	at script(CompositeActivityDefCollSetter:34)
```

Exception in Server:
```
Item called at 2018-09-13 17:00:05.538: requestAction(/entity/3f01a50a-1361-4f1d-969e-260458979088).
ItemImplementation::request(/entity/3f01a50a-1361-4f1d-969e-260458979088) - Transition 0 on workflow/predefined/RemoveSlotFromCollection by /entity/25549805-1991-4b22-812b-f55d0acefb56
ClusterStorageManager.get() - found /entity/3f01a50a-1361-4f1d-969e-260458979088/LifeCycle/workflow in memcache
Workflow::requestAction() - transition:0 step:workflow/predefined/RemoveSlotFromCollection agent:/entity/25549805-1991-4b22-812b-f55d0acefb56
Transition.resolveValue() - returning key 'PredefinedStepOutcome' as 'PredefinedStepOutcome'
Transition.resolveValue() - returning key '0' as '0'
PredefinedStepCollectionBase.unpackParamsAndGetCollection() - params:[Activity, -1, /entity/82598a0e-3ab4-48ad-a827-1b9f4363b8b7]
ClusterStorageManager.get() - found /entity/3f01a50a-1361-4f1d-969e-260458979088/Collection/Activity/last in memcache
ERROR  : CollectionBase - Invalid parameters:[Activity, -1, /entity/82598a0e-3ab4-48ad-a827-1b9f4363b8b7]
EXCEPTION:org.cristalise.kernel.common.ObjectNotFoundException: IDL:org.cristalise.kernel/common/ObjectNotFoundException:1.0  Path does not exist:/domain/-1
	at org.cristalise.storage.jooqdb.lookup.JooqLookupManager.resolvePath(JooqLookupManager.java:254)
	at org.cristalise.kernel.lookup.DomainPath.getItemPath(DomainPath.java:85)
	at org.cristalise.kernel.lifecycle.instance.predefined.PredefinedStepCollectionBase.setChildPath(PredefinedStepCollectionBase.java:69)
	at org.cristalise.kernel.lifecycle.instance.predefined.PredefinedStepCollectionBase.unpackParamsAndGetCollection(PredefinedStepCollectionBase.java:155)
	at org.cristalise.kernel.lifecycle.instance.predefined.RemoveSlotFromCollection.runActivityLogic(RemoveSlotFromCollection.java:50)
	at org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:211)
	at org.cristalise.kernel.lifecycle.instance.Workflow.requestAction(Workflow.java:136)
	at org.cristalise.kernel.entity.ItemImplementation.delegatedAction(ItemImplementation.java:208)
```

**Comment by kovax** [comment]
The actual workflow had a dangling entry int its Activity collection, that is why the Script tried to remove the member. Ths Script needs to be updated to provide the memberID for RemoveSlotFromCollection prefefined step to be fail safe
