### ISSUE TITLE
Build develop branch failed: .XMLClusterStorageTest.checkDirectoryBasedStorage()

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#234]
Build: https://travis-ci.org/cristal-ise/kernel/builds/437203799

```java
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.549 sec <<< FAILURE! - in org.cristalise.kernel.test.persistency.XMLClusterStorageTest
checkDirectoryBasedStorage(org.cristalise.kernel.test.persistency.XMLClusterStorageTest)  Time elapsed: 0.236 sec  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [0]; expected:<[Domain]> but was:<[Item]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:283)
	at org.junit.Assert.assertArrayEquals(Assert.java:298)
	at org.cristalise.kernel.test.persistency.XMLClusterStorageTest.checkXMLClusterStorage(XMLClusterStorageTest.java:77)
	at org.cristalise.kernel.test.persistency.XMLClusterStorageTest.checkDirectoryBasedStorage(XMLClusterStorageTest.java:121)
```

**Comment by kovax** [comment]
It seem that the cluster contents list is returned in different order.
