### ISSUE TITLE
Executing Activity throws an Exception because viewpoint was not found

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#243]
See the exception bellow. The main issue, that the completion of this activity should not trigger any Viewpoint DataHelper. It seem that the workflow engine triggers the Split in the wrong CompositeActivity.

```java
DataHelperUtility.evaluateValue() - pathType:viewpoint dataPath:WorkOrder_ProductionStepQuantity/last://Finished
JooqClusterStorage.get() - uuid:3fa52bfa-9634-4641-b211-cfe537971729 cluster:ViewPoint primaryKeys:[WorkOrder_ProductionStepQuantity, last]
WARNING: JooqClusterStorage.get() - Could NOT fetch '/entity/3fa52bfa-9634-4641-b211-cfe537971729/ViewPoint/WorkOrder_ProductionStepQuantity/last'
ClusterStorageManager.get() - reading ViewPoint/WorkOrder_ProductionStepQuantity/last from JOOQ:POSTGRES ClusterStorage for item /entity/3fa52bfa-9634-4641-b211-cfe537971729
EXCEPTION:org.cristalise.kernel.common.ObjectNotFoundException: IDL:org.cristalise.kernel/common/ObjectNotFoundException:1.0 ClusterStorageManager.get() - Path ViewPoint/WorkOrder_ProductionStepQuantity/last not found in /entity/3fa52bfa-9634-4641-b211-cfe537971729
at org.cristalise.kernel.persistency.ClusterStorageManager.get(ClusterStorageManager.java:313)
at org.cristalise.kernel.persistency.TransactionManager.get(TransactionManager.java:111)
at org.cristalise.kernel.lifecycle.routingHelpers.ViewpointDataHelper.get(ViewpointDataHelper.java:63)
at org.cristalise.kernel.lifecycle.routingHelpers.DataHelperUtility.evaluateValue(DataHelperUtility.java:97)
at org.cristalise.kernel.lifecycle.instance.Split.calculateNexts(Split.java:187)
at org.cristalise.kernel.lifecycle.instance.XOrSplit.runNext(XOrSplit.java:40)
at org.cristalise.kernel.lifecycle.instance.Split.run(Split.java:156)
```

**Comment by kovax** [comment]
Next.getTerminusVertex() is using ca.search() which returned a wrong java object.
