### ISSUE TITLE
Error on CreateItemFromDescription

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#63]
When I tried to create a new ActivityDesc I got the error below (it happens to me 2 times since now).

First I got this one (seems to be related to ApacheDS ? )
```
===========================================================
Item called at 2015-08-27 09:34:16.512: requestAction(/entity/29c73f32-1ac0-4c02-abb0-5d8b76248d57).
ItemImplementation::request(/entity/29c73f32-1ac0-4c02-abb0-5d8b76248d57) - Transition 0 on workflow/predefined/CreateItemFromDescription by /entity/f1bd9a63-9864-4c31-bb65-98818803f4a4
CreateItemFromDescription - Starting.
ERROR  : Unknown Error: requestAction on /entity/29c73f32-1ac0-4c02-abb0-5d8b76248d57 by org.cristalise.kernel.common.SystemKey@148bc79 executing workflow/predefined/CreateItemFromDescription
EXCEPTION:org.cristalise.kernel.common.ObjectCannotBeUpdated: IDL:org.cristalise.kernel/common/ObjectCannotBeUpdated:1.0  OTHER: failed for MessageType : ADD_REQUEST
Message ID : 663
    Add Request :
Entry
    dn[n]: cn=4d8d9c32-6379-48e1-b97f-874dc6d4ef7b,cn=entity,cn=agilium,cn=cristal,dc=dev
    objectclass: cristalentity
    ior: IOR:000000000000002a49444c3a6f72672e6372697374616c6973652e6b65726e656c2f656e746974792f4974656d3a312e30000000000000010000000000000092000102000000000a6c6f63616c686f73740005e100000045afabcb00000000220000000100000001000000000000000200000008526f6f74504f4100000000054974656d00000000000000104d8d9c32637948e1b97f874dc6d4ef7b1400000000000002000000010000001c0000000005010001000000010001010900010109000000010501000100000026000000020002
    cn: 4d8d9c32-6379-48e1-b97f-874dc6d4ef7b
: java.lang.ArrayIndexOutOfBoundsException: -31136:
org.apache.directory.api.ldap.model.exception.LdapException: java.lang.ArrayIndexOutOfBoundsException: -31136
	at org.apache.directory.server.core.partition.impl.btree.AbstractBTreePartition.add(AbstractBTreePartition.java:793)
	at org.apache.directory.server.core.shared.partition.DefaultPartitionNexus.add(DefaultPartitionNexus.java:385)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor$1.add(BaseInterceptor.java:161)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.trigger.TriggerInterceptor.add(TriggerInterceptor.java:300)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.event.EventInterceptor.add(EventInterceptor.java:222)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.subtree.SubentryInterceptor.add(SubentryInterceptor.java:1011)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.collective.CollectiveAttributeInterceptor.add(CollectiveAttributeInterceptor.java:134)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.operational.OperationalAttributeInterceptor.add(OperationalAttributeInterceptor.java:252)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.schema.SchemaInterceptor.add(SchemaInterceptor.java:1095)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.hash.PasswordHashingInterceptor.add(PasswordHashingInterceptor.java:84)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.exception.ExceptionInterceptor.add(ExceptionInterceptor.java:188)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.admin.AdministrativePointInterceptor.add(AdministrativePointInterceptor.java:1201)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.authz.AciAuthorizationInterceptor.add(AciAuthorizationInterceptor.java:516)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.referral.ReferralInterceptor.add(ReferralInterceptor.java:249)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.authn.AuthenticationInterceptor.add(AuthenticationInterceptor.java:335)
	at org.apache.directory.server.core.api.interceptor.BaseInterceptor.next(BaseInterceptor.java:416)
	at org.apache.directory.server.core.normalization.NormalizationInterceptor.add(NormalizationInterceptor.java:127)
	at org.apache.directory.server.core.DefaultOperationManager.add(DefaultOperationManager.java:394)
	at org.apache.directory.server.core.shared.DefaultCoreSession.add(DefaultCoreSession.java:233)
	at org.apache.directory.server.core.shared.DefaultCoreSession.add(DefaultCoreSession.java:217)
	at org.apache.directory.server.ldap.handlers.request.AddRequestHandler.handle(AddRequestHandler.java:57)
	at org.apache.directory.server.ldap.handlers.request.AddRequestHandler.handle(AddRequestHandler.java:39)
	at org.apache.directory.server.ldap.handlers.LdapRequestHandler.handleMessage(LdapRequestHandler.java:206)
	at org.apache.directory.server.ldap.handlers.LdapRequestHandler.handleMessage(LdapRequestHandler.java:55)
	at org.apache.mina.handler.demux.DemuxingIoHandler.messageReceived(DemuxingIoHandler.java:221)
	at org.apache.directory.server.ldap.LdapProtocolHandler.messageReceived(LdapProtocolHandler.java:217)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74)
	at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
	at org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.runTask(UnorderedThreadPoolExecutor.java:474)
	at org.apache.mina.filter.executor.UnorderedThreadPoolExecutor$Worker.run(UnorderedThreadPoolExecutor.java:428)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -31136
	at jdbm.recman.BlockIo.readInt(BlockIo.java:282)
	at jdbm.recman.RecordHeader.getAvailableSize(RecordHeader.java:105)
	at jdbm.recman.PhysicalRowIdManager.allocNew(PhysicalRowIdManager.java:216)
	at jdbm.recman.PhysicalRowIdManager.alloc(PhysicalRowIdManager.java:177)
	at jdbm.recman.PhysicalRowIdManager.update(PhysicalRowIdManager.java:101)
	at jdbm.recman.BaseRecordManager.update(BaseRecordManager.java:281)
	at jdbm.recman.CacheRecordManager.updateCacheEntries(CacheRecordManager.java:417)
	at jdbm.recman.CacheRecordManager.commit(CacheRecordManager.java:349)
	at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmTable.sync(JdbmTable.java:963)
	at org.apache.directory.server.core.partition.impl.btree.jdbm.JdbmPartition.sync(JdbmPartition.java:322)
	at org.apache.directory.server.core.partition.impl.btree.AbstractBTreePartition.add(AbstractBTreePartition.java:784)
	... 46 more

	at org.cristalise.lookup.ldap.LDAPLookup.add(LDAPLookup.java:273)
	at org.cristalise.kernel.lifecycle.instance.predefined.item.CreateItemFromDescription.runActivityLogic(CreateItemFromDescription.java:97)
	at org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:190)
	at org.cristalise.kernel.lifecycle.instance.Workflow.requestAction(Workflow.java:137)
	at org.cristalise.kernel.entity.ItemImplementation.requestAction(ItemImplementation.java:195)
	at org.cristalise.kernel.entity.TraceableEntity.requestAction(TraceableEntity.java:127)
	at org.cristalise.kernel.entity.ItemPOA._invoke(ItemPOA.java:176)
	at com.sun.corba.se.impl.protocol.CorbaServerRequestDispatcherImpl.dispatchToServant(CorbaServerRequestDispatcherImpl.java:654)
	at com.sun.corba.se.impl.protocol.CorbaServerRequestDispatcherImpl.dispatch(CorbaServerRequestDispatcherImpl.java:205)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequestRequest(CorbaMessageMediatorImpl.java:1700)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:1558)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleInput(CorbaMessageMediatorImpl.java:940)
	at com.sun.corba.se.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:198)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:712)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.dispatch(SocketOrChannelConnectionImpl.java:471)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.doWork(SocketOrChannelConnectionImpl.java:1230)
	at com.sun.corba.se.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:490)
	at com.sun.corba.se.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:519)

```

Then at my second try I got :
```
Item called at 2015-08-28 09:00:28.158: requestAction(/entity/29c73f32-1ac0-4c02-abb0-5d8b76248d57).
ItemImplementation::request(/entity/29c73f32-1ac0-4c02-abb0-5d8b76248d57) - Transition 0 on workflow/predefined/CreateItemFromDescription by /entity/f1bd9a63-9864-4c31-bb65-98818803f4a4
CreateItemFromDescription - Starting.
ERROR  : Unknown Error: requestAction on /entity/29c73f32-1ac0-4c02-abb0-5d8b76248d57 by org.cristalise.kernel.common.SystemKey@130b10b executing workflow/predefined/CreateItemFromDescription
EXCEPTION:org.cristalise.kernel.common.ObjectCannotBeUpdated: IDL:org.cristalise.kernel/common/ObjectCannotBeUpdated:1.0  LOOP_DETECT: failed for MessageType : ADD_REQUEST
Message ID : 671
    Add Request :
Entry
    dn[n]: cn=AglSetUserDetails,cn=agilium,cn=ActivityDesc,cn=desc,cn=domain,cn=agilium,cn=cristal,dc=dev
    objectclass: alias
    objectclass: aliasObject
    aliasedObjectName: cn=f35615ef-3fc2-44fc-9e87-c12f0dff8a7b,cn=entity,cn=agilium,cn=cristal,dc=dev
    cn: AglSetUserDetails
: java.lang.ArrayIndexOutOfBoundsException: -31054
	at org.cristalise.lookup.ldap.LDAPLookup.add(LDAPLookup.java:273)
	at org.cristalise.kernel.lifecycle.instance.predefined.item.CreateItemFromDescription.runActivityLogic(CreateItemFromDescription.java:119)
	at org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:190)
	at org.cristalise.kernel.lifecycle.instance.Workflow.requestAction(Workflow.java:137)
	at org.cristalise.kernel.entity.ItemImplementation.requestAction(ItemImplementation.java:195)
	at org.cristalise.kernel.entity.TraceableEntity.requestAction(TraceableEntity.java:127)
	at org.cristalise.kernel.entity.ItemPOA._invoke(ItemPOA.java:176)
	at com.sun.corba.se.impl.protocol.CorbaServerRequestDispatcherImpl.dispatchToServant(CorbaServerRequestDispatcherImpl.java:654)
	at com.sun.corba.se.impl.protocol.CorbaServerRequestDispatcherImpl.dispatch(CorbaServerRequestDispatcherImpl.java:205)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequestRequest(CorbaMessageMediatorImpl.java:1700)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:1558)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleInput(CorbaMessageMediatorImpl.java:940)
	at com.sun.corba.se.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:198)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:712)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.dispatch(SocketOrChannelConnectionImpl.java:471)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.doWork(SocketOrChannelConnectionImpl.java:1230)
	at com.sun.corba.se.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:490)
	at com.sun.corba.se.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:519)
```

**Comment by abranson** [comment]
My guess is that the index in ApacheDS has become corrupted. Will wait for another occurence so we can investigate further.

**Comment by smassonnat** [comment]
I think this might be the consequence of the bug we found regarding domainPath update (in the GUI).

For me it can be closed and if it happens again I will reopen and update this issue.

**Comment by abranson** [comment]
Ok
