### ISSUE TITLE
Script instanciation within an Agent workflow ?

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#73]
I have an Agent with a dedicated workflow : MyUser (instantiated by the predefined step : "CreateAgentFromDescription").

Inside this workflow I have activities with script. I'm able to see all the "jobs", but when I try to complete one which has a script, I got the following error (in GUI log) :
``` 
EXCEPTION:org.cristalise.kernel.scripting.ParameterException: Parameter item is wrong type 
Required: class org.cristalise.kernel.entity.proxy.ItemProxy
Supplied: class org.cristalise.kernel.entity.proxy.AgentProxy
	at org.cristalise.kernel.scripting.Script.setInputParamValue(Script.java:435)
	at org.cristalise.kernel.scripting.Script.<init>(Script.java:152)
	at org.cristalise.kernel.entity.proxy.AgentProxy.callScript(AgentProxy.java:200)
	at org.cristalise.kernel.entity.proxy.AgentProxy.execute(AgentProxy.java:166)
	at org.cristalise.gui.tabs.execution.DefaultExecutor.execute(DefaultExecutor.java:48)
	at org.cristalise.gui.tabs.execution.ActivityViewer.run(ActivityViewer.java:345)
	at java.lang.Thread.run(Thread.java:745)

EXCEPTION:org.cristalise.kernel.common.InvalidDataException: IDL:org.cristalise.kernel/common/InvalidDataException:1.0  Parameter item is wrong type 
Required: class org.cristalise.kernel.entity.proxy.ItemProxy
Supplied: class org.cristalise.kernel.entity.proxy.AgentProxy
	at org.cristalise.kernel.entity.proxy.AgentProxy.execute(AgentProxy.java:176)
	at org.cristalise.gui.tabs.execution.DefaultExecutor.execute(DefaultExecutor.java:48)
	at org.cristalise.gui.tabs.execution.ActivityViewer.run(ActivityViewer.java:345)
	at java.lang.Thread.run(Thread.java:745)

```
 
 Is there some controls that force script to run only on "Item" ?

**Comment by abranson** [comment]
Yes, that matching is looking for an exact match of class, but it should of course accept subclasses. I'll try to change it.

**Comment by smassonnat** [comment]
Ok, but I'm a bit lost because I just realized that I was able to complete another activity of the same workflow : "AglUserSetDetails" without any trouble (see my workflow below).

![bug_kernel_73_workflow](https://cloud.githubusercontent.com/assets/9263650/10220441/da191cf4-6847-11e5-84eb-60e3b22254e0.JPG)

So I don't really understand why it doesn't work with the other activity "AglUserAssignToSite" ...

**Comment by smassonnat** [comment]
Please do not take care of my previous comment => I tried again on the other activity (which I assumed was working fine) and got the same error. ;-)

With the bugfix, everything works fine now. Thanks !
