### ISSUE TITLE
RoutingScript can only use String for input parameter - see RoutingScriptExecSpecs

### ISSUE THREAD

**Issue by kovax** [cristal-ise/kernel#74]
This is because DataHelper.get() returns a String rather than Object.

Split.evaluateScript() - Error: Script CounterScript
EXCEPTION:org.cristalise.kernel.scripting.ParameterException: Parameter counter is wrong type 
Required: class java.lang.Integer
Supplied: class java.lang.String
	at org.cristalise.kernel.scripting.Script.setInputParamValue(Script.java:435)
	at org.cristalise.kernel.lifecycle.instance.WfVertex.evaluateScript(WfVertex.java:213)

**Comment by abranson** [comment]
Yes, all data helper results are Strings, but given that most use of them involves passing them into a loosely typed environment such as Javascript, there's not a lot of benefit to changing it.

However, in the future we could load the schema associated with the referenced outcome, discover the type of the field from that and create the correct object to pass in. But given that the value has already been validated against the schema on submission, this wouldn't add any additional type safety to the script.
