### ISSUE TITLE
Exception during Bootstrap when loading Item of a module 

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/kernel#79]
When I try to import my module "agl-main", I got the following error during bootstrap.
```
Registering module AgiliumngMain
Bootstrap.verifyResource() - Verifying version:'0' type:'Schema' name:'NewCollection'
Module item NewCollection found with path /domain/desc/OutcomeDesc/system/dev/NewCollection. Moving to /domain/desc/OutcomeDesc/system/agilium-main/NewCollection
Bootstrap.verifyResource() - Verifying version:'0' type:'Script' name:'CollDescCreator'
EXCEPTION:java.lang.NullPointerException
	at org.cristalise.kernel.process.Bootstrap.verifyPathAndModuleProperty(Bootstrap.java:331)
	at org.cristalise.kernel.process.Bootstrap.verifyResource(Bootstrap.java:256)
	at org.cristalise.kernel.process.Bootstrap.verifyResource(Bootstrap.java:202)
	at org.cristalise.kernel.process.module.ModuleResource.create(ModuleResource.java:49)
	at org.cristalise.kernel.process.module.Module.importAll(Module.java:115)
	at org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:186)
	at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:114)
	at java.lang.Thread.run(Thread.java:745)

EXCEPTION:org.cristalise.kernel.common.CannotManageException: IDL:org.cristalise.kernel/common/CannotManageException:1.0  Exception verifying module resource agilium-main/CollDescCreator
	at org.cristalise.kernel.process.module.ModuleResource.create(ModuleResource.java:52)
	at org.cristalise.kernel.process.module.Module.importAll(Module.java:115)
	at org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:186)
	at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:114)
	at java.lang.Thread.run(Thread.java:745)

FATAL  : Error importing module resources. Unsafe to continue.
Bootstrap.abort() - Aborting shutdown
```
The "CollDescCreator.xml" file is present in my module at the right place(resources/boot/SC/).

And here is what I have in my LDAP after the bootstrap crashes.
![bug_import_module](https://cloud.githubusercontent.com/assets/9263650/10535952/8c3f7f22-73e7-11e5-8bad-2b4c908d025c.JPG)

The funny thing is that, after a retry without doing any modification it works fine (and block on another item after that ...)

```
Module CristaliseDev registered
Registering module AgiliumngMain
Bootstrap.verifyResource() - Verifying version:'0' type:'Schema' name:'NewCollection'
Module item NewCollection found with path /domain/desc/OutcomeDesc/system/dev/NewCollection. Moving to /domain/desc/OutcomeDesc/system/agilium-main/NewCollection
Bootstrap.verifyResource() - Verifying version:'0' type:'Script' name:'CollDescCreator'
Module item CollDescCreator found with path /domain/desc/Script/system/dev/CollDescCreator. Moving to /domain/desc/Script/system/agilium-main/CollDescCreator
Bootstrap.verifyResource() - Verifying version:'0' type:'ElementaryActivityDef' name:'DefineNewCollection'
[...]
===========================================================
Item called at 2015-10-16 09:24:21.725: initialise(/entity/b9e5ed74-5e2c-412b-8973-af79d97c11bc).
Bootstrap.checkToStoreOutcomeVersion() - AglSiteRemoveFromUser ElementaryActivityDef v0 not found! Attempting to insert new.
Bootstrap.storeOutcomeEventAndViews() - Writing new ElementaryActivityDef v0
Bootstrap.verifyResource() - Verifying version:'0' type:'Schema' name:'AglSiteAssignToUser'
EXCEPTION:java.lang.NullPointerException
	at org.cristalise.kernel.process.Bootstrap.verifyPathAndModuleProperty(Bootstrap.java:331)
	at org.cristalise.kernel.process.Bootstrap.verifyResource(Bootstrap.java:256)
	at org.cristalise.kernel.process.Bootstrap.verifyResource(Bootstrap.java:202)
	at org.cristalise.kernel.process.module.ModuleResource.create(ModuleResource.java:49)
	at org.cristalise.kernel.process.module.Module.importAll(Module.java:115)
	at org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:186)
	at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:114)
	at java.lang.Thread.run(Thread.java:745)

EXCEPTION:org.cristalise.kernel.common.CannotManageException: IDL:org.cristalise.kernel/common/CannotManageException:1.0  Exception verifying module resource agilium-main/AglSiteAssignToUser
	at org.cristalise.kernel.process.module.ModuleResource.create(ModuleResource.java:52)
	at org.cristalise.kernel.process.module.Module.importAll(Module.java:115)
	at org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:186)
	at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:114)
	at java.lang.Thread.run(Thread.java:745)

FATAL  : Error importing module resources. Unsafe to continue.
```
![bug_import_module_2](https://cloud.githubusercontent.com/assets/9263650/10536051/51565f56-73e8-11e5-902c-d012e9c27c21.JPG)

**Comment by abranson** [comment]
Seems to be just a missing null check, but I don't know why it's not caused problems before. See if that commit helps.

**Comment by abranson** [comment]
Assuming it did help :)
